### ISSUE TITLE
Unsupported libc version - OSX 

### ISSUE THREAD

**Issue by looneym** [markdownreveal/markdownreveal#29]
### Description

Attempting to run any commands fails with this stack trace:

```python
(venv)  ✘  ~/gr   up  mdr --help
Traceback (most recent call last):
  File "/Users/Micheal/markdownreveal/venv/bin/mdr", line 11, in <module>
    load_entry_point('markdownreveal', 'console_scripts', 'mdr')()
  File "/Users/Micheal/markdownreveal/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/Micheal/markdownreveal/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2752, in load_entry_point
    return ep.load()
  File "/Users/Micheal/markdownreveal/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2405, in load
    return self.resolve()
  File "/Users/Micheal/markdownreveal/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2411, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/Micheal/markdownreveal/markdownreveal/commands.py", line 21, in <module>
    from .convert import Handler
  File "/Users/Micheal/markdownreveal/markdownreveal/convert.py", line 7, in <module>
    from watchdog.observers.inotify_buffer import InotifyBuffer
  File "/Users/Micheal/markdownreveal/venv/lib/python3.6/site-packages/watchdog/observers/inotify_buffer.py", line 20, in <module>
    from watchdog.observers.inotify_c import Inotify
  File "/Users/Micheal/markdownreveal/venv/lib/python3.6/site-packages/watchdog/observers/inotify_c.py", line 55, in <module>
    raise UnsupportedLibc("Unsupported libc version found: %s" % libc._name)
watchdog.utils.UnsupportedLibc: Unsupported libc version found: /usr/lib/libc.dylib
```

### Details:
- Python 3.6.3
- OSX 10.11.6

### Workaround

Commenting out these lines in `markdownreveal/convert.py ` prevents the import and seems to have no impact on the program?

```python 
from watchdog.observers.inotify_buffer import InotifyBuffer
...
InotifyBuffer.delay = 0.1
```

***

Given that inotify is linux-specific and the install docs do not specify that this program requires linux - can we modify the docs to reflect this or implement some conditional logic to prvent loading this buffer on non-linux systems?

**Comment by Peque** [comment]
Thanks for reporting this bug! :blush:

I implemented a fix in #30. Can you verify it works fine for you?
