### ISSUE TITLE
Running on Windows 10 produces a FileNotFound error

### ISSUE THREAD

**Issue by mer0mingian** [markdownreveal/markdownreveal#40]
At first I got stuck with symlink errors, which seems to be a general Python problem, when not running in developer mode. However, even then I get:

> (base) C:\Users\minged01>mdr presentation.md
> Traceback (most recent call last):
>   File "c:\programs2\miniconda\lib\runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "c:\programs2\miniconda\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\minged01\AppData\Roaming\Python\Python37\Scripts\mdr.exe\__main__.py", line 9, in <module>
>   File "c:\programs2\miniconda\lib\site-packages\click\core.py", line 764, in __call__
>     return self.main(*args, **kwargs)
>   File "c:\programs2\miniconda\lib\site-packages\click\core.py", line 717, in main
>     rv = self.invoke(ctx)
>   File "c:\programs2\miniconda\lib\site-packages\click\core.py", line 1137, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "c:\programs2\miniconda\lib\site-packages\click\core.py", line 956, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "c:\programs2\miniconda\lib\site-packages\click\core.py", line 555, in invoke
>     return callback(*args, **kwargs)
>   File "C:\Users\minged01\AppData\Roaming\Python\Python37\site-packages\markdownreveal\commands.py", line 53, in show
>     generate(markdown_file)
>   File "C:\Users\minged01\AppData\Roaming\Python\Python37\site-packages\markdownreveal\convert.py", line 136, in generate
>     check_output(command)
>   File "c:\programs2\miniconda\lib\subprocess.py", line 389, in check_output
>     **kwargs).stdout
>   File "c:\programs2\miniconda\lib\subprocess.py", line 466, in run
>     with Popen(*popenargs, **kwargs) as process:
>   File "c:\programs2\miniconda\lib\subprocess.py", line 769, in __init__
>     restore_signals, start_new_session)
>   File "c:\programs2\miniconda\lib\subprocess.py", line 1172, in _execute_child
>     startupinfo)
> FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden

Install path has been added to the system environment path variable.
Any ideas what is happening here? Thanks in advance!

**Comment by Peque** [comment]
I do not have a Windows machine at hand to try it, only Linux. Would you mind providing more information?

- Python version (`python --version`)
- Markdownreveal version (`mdr --version`); upgrade to 0.3.0 if not using that version already

**Comment by Peque** [comment]
I just had a look at it and it may be the fact that Markdownreveal is using `rsync`, which is not available from Windows by default.

I would recommend you to use the [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/about) when using Markdownreveal. :innocent:

**Comment by Peque** [comment]
Unfortunately, I do not use Windows (only Linux) so I cannot currently support this operating system.

I would be willing to accept pull-requests fixing this issue and any other Windows-compatibility issues though, if someone wants to contribute them to the project. :blush:

**Comment by mer0mingian** [comment]
Hi Peque, thanks for the suggestions! I will try to look into this within the next week and make a pull request - if I can convince my company's IT dep to allow virtualisation ;)

**Comment by Daniel-at-github** [comment]
It's possible to try windows for free with a [vagrant box](https://github.com/jborean93/ansible-windows/tree/master/vagrant), but it's better (IMHO) to go the Linux route. You could use:
* Virtualization.
* [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
* [Containers](https://docs.docker.com/docker-for-windows/install/)

**Comment by gkmngrgn** [comment]
Hi @Peque, I'm a Windows user and I can help you with this issue. I investigated all OS-specific problems and I need to do some important changes affecting the codebase, that would be nice if we discuss all the steps:

1. Pandoc is available on Windows but can't we get rid of rsync? Or we can add a second `generate` function just for the Windows platform, but this function will be possible to work on all platforms. What do you think?
2. `symlink_to` needs extra permissions on Windows, so we can prefer copy/paste directories instead. Or maybe it's better to try symlink at first, then copy/paste.
3. Finally, we can prepare a conda package for markdownreveal, I think @mer0mingian is a miniconda user and maybe data science community needs an easy-installable version of this project.

**Comment by Peque** [comment]
@gkmngrgn Thanks for taking a look at it.

1. That sounds like a very reasonable approach. If `rsync` is available, we use it, otherwise we use another synchronization function. Later, after we try the new function, I would be willing to leave it as the default/only approach if performance is not too much worse compared to the `rsync` alternative.
1. Copying should definitely not be the default behavior. Did not know about any extra permissions on Windows (the [documentation](https://docs.python.org/3/library/pathlib.html#pathlib.Path.symlink_to) does not seem to mention that). Which exception is raised on Windows?
1. Conda is indeed very popular, so that could be nice to have. In fact, Conda may help packaging/installing some binary dependencies like Pandoc.

**Comment by gkmngrgn** [comment]
Hi @Peque, thanks for the reply.

1. Ok so we can keep `rsync` for the other platforms, but if the command is not available, we will try a second way to fetch the requirements.
2. I think Python documentation suppose that all Windows users have admin privileges. The other way to use symbolic links is to activate developer mode. You can see the output on the bottom of my message. Also here you can see some alternative solutions of this problem.
https://stackoverflow.com/questions/1447575/symlinks-on-windows
3. Yep, but first we have to solve Windows specific problems before packaging it :-/

---

**Output for the point 2:**

```
Traceback (most recent call last):
  File "C:\Users\user\markdownreveal\venv\Scripts\markdownreveal-script.py", line 11, in <module>
    load_entry_point('markdownreveal==0.3.0', 'console_scripts', 'markdownreveal')()
  File "C:\Users\user\markdownreveal\venv\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\user\markdownreveal\venv\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "C:\Users\user\markdownreveal\venv\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\user\markdownreveal\venv\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\user\markdownreveal\venv\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\user\markdownreveal\venv\lib\site-packages\markdownreveal-0.3.0-py3.7.egg\markdownreveal\commands.py", line 53, in show
  File "C:\Users\user\markdownreveal\venv\lib\site-packages\markdownreveal-0.3.0-py3.7.egg\markdownreveal\convert.py", line 122, in generate
  File "C:\Users\user\markdownreveal\venv\lib\site-packages\markdownreveal-0.3.0-py3.7.egg\markdownreveal\local.py", line 166, in initialize_localdir
  File "C:\Users\user\markdownreveal\venv\lib\site-packages\markdownreveal-0.3.0-py3.7.egg\markdownreveal\local.py", line 104, in initialize_localdir_project
  File "c:\Users\user\appdata\local\programs\python\python37\Lib\pathlib.py", line 1337, in symlink_to
    self._accessor.symlink(target, self, target_is_directory)
OSError: symbolic link privilege not held
```

**Comment by Peque** [comment]
@gkmngrgn I am fine with doing a platform check then: if Windows, then copy instead of symlink (or whatever alternative you come up with).

It would be great to integrate AppVeyor if we are going to support Windows. Ideally, the AppVeyor integration should come first (the tests would fail because of that symlink error). Then you could push the changes to fix that issue so we can merge them.
