### ISSUE TITLE
HTTP 404 error on reload

### ISSUE THREAD

**Issue by Peque** [markdownreveal/markdownreveal#41]
It seems the presentation view in the browser is not automatically updated on code/files change, as expected.

Instead, this is shown on the browser:

```
Traceback (most recent call last):
  File "/container/miniconda/envs/python37/lib/python3.7/site-packages/tornado/web.py", line 1699, in _execute
    result = await result
  File "/container/miniconda/envs/python37/lib/python3.7/site-packages/tornado/web.py", line 2577, in get
    self.absolute_path = self.validate_absolute_path(self.root, absolute_path)
  File "/container/miniconda/envs/python37/lib/python3.7/site-packages/tornado/web.py", line 2779, in validate_absolute_path
    raise HTTPError(404)
tornado.web.HTTPError: HTTP 404: Not Found
```

Reloading the browser is enough (i.e.: Markdownreveal does not really crash).

**Comment by sakethramanujam** [comment]
any steps to reproduce this?
I'd like to take a look at it and fix it. ie., asking to assign me this issue.

**Comment by Peque** [comment]
@sakethramanujam Yeah:

- Install Markdownreveal on a fresh environment with Python 3.6+
- `mdr presentation.md` to open the presentation on your browser
- Edit and save changes in `presentation.md`

That should trigger the error. You can use this presentation as an example (maybe it only occurs with "big" presentations, I do not know):

https://github.com/Peque/PyConES-Spain-2019-tools
